version: "3"
services:
  db:
    image: postgres:12-alpine
    container_name: postgres
    volumes:
      - .:/app
      - ./.database/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: bank_system
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ultraSafePass
    ports:
      - 5464:5432
    restart: unless-stopped
  jdk:
    image: maven:3.5-jdk-8-alpine
    container_name: jdk
    working_dir: /app
    volumes:
      - .:/app
      - ~/.m2:/root/.m2
    ports:
      - 8808:8080
    command: ./mvnw clean spring-boot:run
    restart: unless-stopped
    depends_on:
      - db