spring:
  datasource:
    url: jdbc:postgresql://db/bank_system
    username: postgres
    password: ultraSafePass
  flyway:
    validate-on-migrate: true
  mvc:
    view:
      prefix: /jsp/
      suffix: .jsp